# Generated by Django 3.2.8 on 2021-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('ImgId', models.AutoField(primary_key=True, serialize=False)),
                ('ImgName', models.CharField(max_length=500)),
                ('ImgURL', models.URLField(max_length=500)),
                ('ImgDetails', models.TextField(max_length=500)),
            ],
        ),
    ]
